"""Add level and file_count columns to Feed model

Revision ID: 0cbc75b57ebd
Revises: 79adee07af08
Create Date: 2025-04-09 12:02:37.635746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbc75b57ebd'
down_revision = '79adee07af08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('file_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_column('file_count')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
