flask db upgrade"""Add description field to Reel model

Revision ID: 54c4e789b376
Revises: 2671c120a43d
Create Date: 2025-04-12 09:50:16.677378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c4e789b376'
down_revision = '2671c120a43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
